OGRE: OgreXSIHelper.h File Reference
OgreXSIHelper.h File Reference
#include <xsi_application.h>
#include <xsi_string.h>
#include <xsi_x3dobject.h>
#include <xsi_vertexcolor.h>
#include <xsi_math.h>
#include <xsi_ref.h>
#include <xsi_actionsource.h>
#include <xsi_animationsourceitem.h>
#include <xsi_progressbar.h>
#include <xsi_uitoolkit.h>
#include <xsi_shader.h>
#include <xsi_value.h>
#include <stdlib.h>
#include "OgrePrerequisites.h"
#include "OgreString.h"
#include "OgreColourValue.h"
#include "OgreLogManager.h"
#include "OgreStringVector.h"
#include "OgreSingleton.h"
#include "OgreVector3.h"
#include "OgreQuaternion.h"
#include "OgreHardwareVertexBuffer.h"
Classes
struct Ogre::AnimationEntry
An entry for animation; allows the userto split the timeline into multiple separate animations.
class Ogre::DeformerEntry
An entry for a Deformer - need original index because this will be boneID.
struct Ogre::MaterialEntry
Record of an XSI GL shader material.
struct Ogre::PassEntry
Record of XSI details that are to become a pass.
class Ogre::ProgressManager
Namespaces
Ogre
Undefine in <sys/endian.h> defined bswap macros for FreeBSD.
Macros
#define OGRE_XSI_NUM_MESH_STEPS 200
Typedefs
typedef std::list< AnimationEntry > Ogre::AnimationList
List of animations.
typedef std::map< String, DeformerEntry * > Ogre::DeformerMap
Map from deformer name to deformer entry.
typedef std::map< String, MaterialEntry * > Ogre::MaterialMap
Map from material name to material entry.
typedef std::deque< PassEntry * > Ogre::PassQueue
typedef std::map< String, int > Ogre::TextureProjectionMap
Map from texture projection name to index.
Enumerations
enum Ogre::XSITrackType {
Ogre::XTT_POS_X = 0, Ogre::XTT_POS_Y = 1, Ogre::XTT_POS_Z = 2, Ogre::XTT_ROT_X = 3,
Ogre::XTT_ROT_Y = 4, Ogre::XTT_ROT_Z = 5, Ogre::XTT_SCL_X = 6, Ogre::XTT_SCL_Y = 7,
Ogre::XTT_SCL_Z = 8, Ogre::XTT_COUNT = 9
}
Functions
void Ogre::copyFile (const String &src, const String &dest)
Platform-independent file copy (destination folder must exist) Maybe use Boost::filesystem if this gets out of hand.
void LogOgreAndXSI (const char *msg)
void LogOgreAndXSI (const Ogre::String &msg)
void LogOgreAndXSI (const XSI::CString &msg)
XSI::CString OgretoXSI (const Ogre::String &str)
Useful function to convert an Ogre String to an XSI CString.
Ogre::String XSItoOgre (const XSI::CString &xsistr)
Useful function to convert XSI CValue to an Ogre String.
Ogre::RGBA XSItoOgre (const XSI::CVertexColor &xsiColour)
Ogre::Quaternion XSItoOgre (const XSI::MATH::CQuaternion &xsiQuat)
Ogre::Vector3 XSItoOgre (const XSI::MATH::CVector3 &xsiVec)
Macro Definition Documentation
OGRE_XSI_NUM_MESH_STEPS
#define OGRE_XSI_NUM_MESH_STEPS 200
Function Documentation
LogOgreAndXSI() [1/3]
void LogOgreAndXSI (const char * msg) inline
References LogOgreAndXSI().
LogOgreAndXSI() [2/3]
void LogOgreAndXSI (const Ogre::String & msg) inline
References Ogre::LogManager::getSingleton(), Ogre::LogManager::logMessage(), and OgretoXSI().
Referenced by LogOgreAndXSI().
LogOgreAndXSI() [3/3]
void LogOgreAndXSI (const XSI::CString & msg) inline
References Ogre::LogManager::getSingleton(), Ogre::LogManager::logMessage(), and XSItoOgre().
OgretoXSI()
XSI::CString OgretoXSI (const Ogre::String & str) inline
Useful function to convert an Ogre String to an XSI CString.
Referenced by LogOgreAndXSI().
XSItoOgre() [1/4]
Ogre::String XSItoOgre (const XSI::CString & xsistr) inline
Useful function to convert XSI CValue to an Ogre String.
Useful function to convert an XSI CString to an Ogre String
References Ogre::BLANKSTRING.
Referenced by LogOgreAndXSI().
XSItoOgre() [2/4]
Ogre::RGBA XSItoOgre (const XSI::CVertexColor & xsiColour) inline
XSItoOgre() [3/4]
Ogre::Quaternion XSItoOgre (const XSI::MATH::CQuaternion & xsiQuat) inline
XSItoOgre() [4/4]
Ogre::Vector3 XSItoOgre (const XSI::MATH::CVector3 & xsiVec) inline