name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:  '*'
  pull_request:
    branches: '*'

env:
  INPUT: "Components Docs/src/SettingUpOgre/SettingUpOgre.md Docs/src/SettingUpOgre/SettingUpOgreLinux.md Docs/src/SettingUpOgre/SettingUpOgreWindows.md Docs/src/SettingUpOgre/SettingUpOgre_iOS.md Docs/src/SettingUpOgre/SettingUpOgre_macOS.md Docs/src/UsingOgre/UsingOgreInYourApp.md Docs/src/apimainpage.md Docs/src/manual/BehaviorOfStagingTexturesD3D11.md Docs/src/manual/Ogre2.2.Changes.md Docs/src/manual/azdo.md Docs/src/manual/changes.md Docs/src/manual/commandbuffer.md Docs/src/manual/compositor.md Docs/src/manual/hlms.md Docs/src/manual/instancing.md Docs/src/manual/manual.md Docs/src/manual/performance.md Docs/src/manual/tech.md Docs/src/manual/threading.md OgreMain PlugIns RenderSystems"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1

      - name: Generate docs with doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: './Doxyfile'
          working-dir: '/home/runner/work/ogre-next/ogre-next'

      - name: Publish
        if: github.ref == 'master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
